[build]
  command = "npm run build"
  publish = "build"  # Direktori tempat hasil build proyek React akan disimpan

[dev]
  command = "npm run start"
  functions = "lambda"  # Direktori tempat fungsi Netlify serverless akan ditempatkan

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3001/:splat"
  status = 200
  force = true
